### ISSUE TITLE
Double clicking on host name in Web client problem

### ISSUE THREAD

**Issue by kadrika** [centreon/centreon-map#13]
Hi,

If I have added a host to view and when I double click on it in the web interface it open a new tab and there it shows me You are not allowed to reach this page. I am logged in as admin user.

**Comment by centreonmap** [comment]
Hey Kadri,
This bug has already been fixed in centreon-map4-web-client 0.13.2.
Please just update your module on your Centreon server with command
# yum update centreon-map4-web-client
Then in Centreon Web ui > Administrations > Extensions
Regards
