### ISSUE TITLE
Hosts services have 5x duplicates

### ISSUE THREAD

**Issue by kadrika** [centreon/centreon-map#14]
Hi,

We just updated the MAP server to newest version and now we have another problem. When clicking on the host in the client view the services are multiplied by 5.
<img width="891" alt="screen shot 2016-02-02 at 3 30 57 pm" src="https://cloud.githubusercontent.com/assets/12610733/12750889/8b9ce3f8-c9c2-11e5-9b5e-452424a3029f.png">

**Comment by centreonmap** [comment]
Hey Kadri,
That's a know bug, the worst one of them.
We are currently working on it. The workaround is to remove all services within the host, they will be created again a few minutes later.
This problem can generate performance issues on server.
It will be fixed as soon as we can.

**Comment by centreonmap** [comment]
Hey Kadri,
we have finally fixed this bug, the version will be released in beta next week !

I close your ticket, thanks for your feedback.
