### ISSUE TITLE
rpm packages not available

### ISSUE THREAD

**Issue by CFRR** [centreon/centreon-map#16]
I'm trying install the centreon-map following the [instruction  ](https://github.com/centreon/centreon-map/blob/master/doc/en/installation/from_packages/server.rst) but no rpm packages not available.
can anyone help?
Thx
```
# yum install centreon-map4-server
Loaded plugins: fastestmirror, rhnplugin, security
This system is receiving updates from RHN Classic or Red Hat Satellite.
Setting up Install Process
Loading mirror speeds from cached hostfile
 * base: centos.cadt.com
 * extras: centos.cadt.com
 * rpmforge: apt.sw.be
 * updates: centos.cadt.com
No package centreon-map4-server available.
Error: Nothing to do
#
```

**Comment by centreonmap** [comment]
Hello,

the Centreon Map 4 packets are on the Centreon Map 3 repository.
Do you actually have access to it ?

Regards,
Pierre GAUTIER

**Comment by CFRR** [comment]
I don't think so, can you please provide the url for this repository?
Thx

**Comment by centreonmap** [comment]
Centreon Map 3 and 4 are commercial products, I cannot provide it to you like this.
If you are a Centreon Map 3 client you will find the repository on our professional support platform : https://support.centreon.com/
If you are not, regrettably you will have to wait for the official release and purchase it :)

**Comment by bcournaud** [comment]
Hi @CFRR,

Since your issue is not related to any bug or feature, I will close it.
Feel free to come back here and open any tickets if you purchase a Map 4 license !

Best regards,

Bertrand Cournaud
