### ISSUE TITLE
MAP4 License 

### ISSUE THREAD

**Issue by kadrika** [centreon/centreon-map#17]
Hi,

After updating the map this morning the client says that the license is over. So is the Beta testing officially over?

**Comment by centreonmap** [comment]
Hello Kadri,

we've just released a version 0.20.0 which includes a license valid until march 15h.

Please follow the document to update your server : https://documentation.centreon.com/docs/centreon-map-4/en/latest/upgrade/from_packages.html#centreon-map-4-server

Regards,
Pierre GAUTIER
