### ISSUE TITLE
Centreon web dont show map4 views after upgrade to the last version.

### ISSUE THREAD

**Issue by pavelsmn** [centreon/centreon-map#18]
Centreon 2.7.1
Map4 0.20.0-1  / map4-web  0.13.2

httpd error_log:
[error] [client xx.xx.xx.xx] File does not exist: /var/www/html/centreon-studio, referer: https://xx.xx.xx.xx/centreon/main.php?p=288

tomcat6 error_log:

[STUDIO][03/03 11:01:01,877][ERROR ] [Broker] Error.                                                                                      [com.centreon.studio.map.server.business.broker.bbdo.BrokerEventProducerRunnable][CentreonBrokerEventHandler]  
com.centreon.studio.map.server.business.broker.bbdo.io.exception.BrokerReadException: [BBDO] Empty stream (len=-1)

I can login trough map4 desktop client and modify views, but in centreon I can see only the blank page.

**Comment by centreonmap** [comment]
Hi Pavel,

It seems to be an issue we don't know, I can propose you to have a webex session to check it up.
Can you please open a ticket on our support platform so I can follow the issue and send you the webex link ?

Regards,
Pierre GAUTIER
