### ISSUE TITLE
Le copier/coller ne fonctionne qu'une seul fois 

### ISSUE THREAD

**Issue by ddu17** [centreon/centreon-map#19]
Bonjour,

J'utilise la dernière version stable de Centreon MAP 4.

Je remarque que le copier/coller d'objet ne fonctionne qu'une seule fois.

Par exemple, je place une forme dans mon espace de travail. J'appuie sur ctrl-c et ctrl-v pour la copier/coller. Je souhaite la coller une nouvelle fois, j'appuie alors sur ctrl-v, mais là rien ne se passe. Pour copier/coller, je dois de nouveau appuyer sur ctrl-c et ctrl-v.

Cordialement.

Damien Duponchelle

**Comment by centreonmap** [comment]
Fixed in version 4.0.3
