### ISSUE TITLE
Gestion du port MySQL

### ISSUE THREAD

**Issue by Supervision-Macif** [centreon/centreon-map#2]
Bonjour,

Le script de configuration ./configuration.sh ne propose pas de modifier le port d'accès à la base de données.

**Comment by centreonmap** [comment]
La gestion du port des 3 bases de données (centreon, centreon_storage, centreon_studio) a été ajoutée au script de configuration.
Il sera disponible dans le RPM de la version 0.13.1 du server.
Merci pour votre retour.
