### ISSUE TITLE
Unable to choose view in MAP4 widget

### ISSUE THREAD

**Issue by kadrika** [centreon/centreon-map#22]
Hi,

When using MAP4 widget there is no option to choose view to be shown. All views "icons" are shown, but I cant choose one specific. I am using widget version:  	4.0.1.

![screen shot 2016-04-19 at 9 17 20 am](https://cloud.githubusercontent.com/assets/12610733/14629468/99bebfc2-060f-11e6-8e90-6e16cb1397b7.png)

**Comment by bcournaud** [comment]
Hi Kadrika,

If you enter a view you should see a "Save" button on the top right corner of the widget.
It will save the view and also the zoom level and the position of the view.

If you don't see this button try cleaning your cache.

Let me know if it's working.

![selection_188](https://cloud.githubusercontent.com/assets/13016403/14630160/171f4fb2-060c-11e6-9665-68f9a98b9882.png)

**Comment by kadrika** [comment]
Thanks, I did not notice the Save button before. It works great! Thanks again! You may close this issue.

**Comment by bcournaud** [comment]
Glad I could help !

Have a good day
