### ISSUE TITLE
Host with acknowledged service shown as red on the map

### ISSUE THREAD

**Issue by kadrika** [centreon/centreon-map#24]
Hi,

Can you change the logic of how the acknowledged services are shown in the maps. In old Map v3 if the service that was critical was acknowledged the map showed green. But with Map v4 if I acknowledge a service the map will have small blue icon on the corner but container will still show red. It is quite annoying and make hard to understand if there are new alarms or not.
<img width="87" alt="screen shot 2016-05-17 at 1 28 05 pm" src="https://cloud.githubusercontent.com/assets/12610733/15319392/45d5f166-1c33-11e6-95e7-d8776249d884.png">

**Comment by bcournaud** [comment]
Hi kadri,

It's actually possible to do that through the configuration file, although we didn't documented this part yet.
You can decide whether or not you want to ignore downtime elements, acknowledge elements of use hard state of soft state.

To do so, go into your Map 4 server and edit the file /etc/centreon-studio/studio-config.properties

Add these lines at the end of the file (skip the parentheses part):

```
drilldown.useHardState = false (this is the default value)
drilldown.ignoreElementInDowntime = true (the default value is false)
drilldown.ignoreElementAcknowledged = true (the default value is false)
```

If they are not set in the file, Map 4 will use default values.

Then restart your Map 4 server (service tomcat6 restart)

Please tell us if adding these parameters did solved your issue.

Best regards,

**Comment by kadrika** [comment]
Thanks, it works!

**Comment by bcournaud** [comment]
Great ! We will add it to the documentation soon.

Have a good day !
