### ISSUE TITLE
Link lines in French

### ISSUE THREAD

**Issue by kadrika** [centreon/centreon-map#3]
Hi, 
In new map 4, the link lines are in French.
<img width="900" alt="screen shot 2016-01-21 at 4 14 15 pm" src="https://cloud.githubusercontent.com/assets/12610733/12482803/57351ac0-c05a-11e5-9b38-448e8a787a7d.png">

**Comment by centreonmap** [comment]
Thanks for your feedback, it will be fixed in the next release.

**Comment by centreonmap** [comment]
It has been fixed, and will be deployed in the next automatic release.

**Comment by centreonmap** [comment]
Hey Kadri,
Have you been able to update your desktop ?
Do you confirm this issue can be closed ?
Regards

**Comment by kadrika** [comment]
Hi, not yet, but give me few minutes. As I am using MacOS myself I need to update the client on the other PC. 
So I am really hoping to see the client for MacOS as soon as possible :)

**Comment by kadrika** [comment]
Yes, this issue is resolved.
