### ISSUE TITLE
Adding images to frontend and desktop client

### ISSUE THREAD

**Issue by kadrika** [centreon/centreon-map#4]
Hi,

I noticed that when I add folder or file to frontend or to desktop client they do not sync. The files I have added to frontend media folder are missing from the dektop client and the images I have added to client are missing from the frontend.  When pushing sync button on the web it says 0 images were synced.
![screen shot 2016-01-21 at 4 48 58 pm](https://cloud.githubusercontent.com/assets/12610733/12483648/ea09bd2a-c05e-11e5-8534-b92ca8fefeb7.png)

**Comment by centreonmap** [comment]
Hey Kadri,
For the moment, the 2 libraries are distinct. It implies that until we merge them images from Centreon cannot be used in Centreon Map and vice versa.
We are aware that it's an important limitation and plan to correct it as soon as possible.

**Comment by kadrika** [comment]
Thanks for the reply!

**Comment by centreonmap** [comment]
Hey Kadri,
hosts that have an image in Centreon have it now in Centreon Map 4, the next release scheduled for the next week will include that fix.
Thanks for your feedback.
