### ISSUE TITLE
Login error

### ISSUE THREAD

**Issue by kadrika** [centreon/centreon-map#6]
Every time I login to desktop client error is displayed.
<img width="441" alt="screen shot 2016-01-21 at 5 06 57 pm" src="https://cloud.githubusercontent.com/assets/12610733/12484149/892ff548-c061-11e5-948c-262d6cfcd762.png">

**Comment by centreonmap** [comment]
Can you attach to this ticket your Centreon-Map4.log file ?
By default it's located in C:\Users\xxx\Centreon-Map4\logs\

**Comment by kadrika** [comment]
Sure. 
But I cant add it here, as Github says: Unfortunately, we don’t support that file type.  Try again with a PNG, GIF, JPG, DOCX, PPTX, XLSX, TXT, PDF, or ZIP. Is it ok, if I add it to the ticket we have open in Centreon Support?

**Comment by kadrika** [comment]
[Centreon-Map4 log.pdf](https://github.com/centreon/centreon-map/files/100352/Centreon-Map4.log.pdf)
 I changed the .log to .pdf so when opening it, just change it back to .log

**Comment by centreonmap** [comment]
Sorry for my late response.
It seems to be linked to server metaservices acl bug that has been fixed.
Version 0.13.1 of server and desktop client are to be release soon.
Could tell me if they fix this issue ?
